# Generated by Django 5.2.6 on 2025-10-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("prompt", "Prompt"),
                            ("proofreader", "Proofreader"),
                            ("summarizer", "Summarizer"),
                            ("translator", "Translator"),
                            ("writer", "Writer"),
                            ("rewriter", "Rewriter"),
                        ],
                        default="prompt",
                        max_length=255,
                    ),
                ),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
