# Generated by Django 5.2.6 on 2025-10-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatrecord",
            name="api_key",
            field=models.CharField(default="", max_length=255),
        ),
    ]
