# Generated by Django 5.2.6 on 2025-10-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_chatrecord_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="RagChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("embedding", models.JSONField(default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="chatrecord",
            name="method",
            field=models.CharField(
                choices=[
                    ("prompt", "Prompt"),
                    ("proofreader", "Proofreader"),
                    ("summarizer", "Summarizer"),
                    ("translator", "Translator"),
                    ("writer", "Writer"),
                    ("rewriter", "Rewriter"),
                    ("explainer", "Explainer"),
                    ("copywriting", "Copywriting"),
                    ("document_ai", "Document AI"),
                    ("rag_chat", "RAG Chat"),
                ],
                default="prompt",
                max_length=255,
            ),
        ),
    ]
