# Generated by Django 5.2.6 on 2025-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ragchunk_alter_chatrecord_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatrecord",
            name="method",
            field=models.CharField(
                choices=[
                    ("prompt", "Prompt"),
                    ("proofreader", "Proofreader"),
                    ("summarizer", "Summarizer"),
                    ("translator", "Translator"),
                    ("writer", "Writer"),
                    ("rewriter", "Rewriter"),
                    ("explainer", "Explainer"),
                    ("copywriting", "Copywriting"),
                    ("document_ai", "Document AI"),
                    ("email_generator", "Email Generator"),
                    ("rag_chat", "RAG Chat"),
                    ("email_generation", "Email Generation"),
                ],
                default="prompt",
                max_length=255,
            ),
        ),
    ]
